[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "postgresql",
  "libpqxx",
  "gcc"
]

[phases.install]
cmds = [
  "apt-get update",
  "apt-get install -y postgresql-client libpq-dev",
  "cd backend && pip install --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = ["cd backend && python -c 'import app.main'"]  # простая проверка импорта

[start]
cmd = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHON_VERSION = "3.11"
